# Generated by Django 5.0.1 on 2026-08-12 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
        ('projects', '0002_projectasset_content_alter_projectasset_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='enterprise.organization'),
        ),
    ]
