# Generated by Django 5.0.1 on 2026-08-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectasset',
            name='file',
            field=models.FileField(blank=True, upload_to='project_assets/%Y/%m/'),
        ),
    ]
