# Generated by Django 5.0.1 on 2026-06-17 09:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_slug', models.SlugField(max_length=100)),
                ('status', models.CharField(choices=[('pending', '等待'), ('running', '运行中'), ('done', '完成'), ('error', '错误'), ('stopped', '已停止')], default='pending', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runner_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_runner_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
