# Generated by Django 5.0.1 on 2026-08-12 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_runner', '0002_job_attempt_job_heartbeat_at_job_max_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence', models.PositiveBigIntegerField()),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app_runner.job')),
            ],
            options={
                'db_table': 'app_runner_job_events',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='jobevent',
            constraint=models.UniqueConstraint(fields=('job', 'sequence'), name='unique_job_event_sequence'),
        ),
    ]
