# Generated by Django 5.0.1 on 2026-09-05 09:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('enterprise', '0005_external_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'application_categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('developer', models.CharField(blank=True, default='', max_length=100)),
                ('screenshots', models.JSONField(blank=True, default=list)),
                ('usage_count', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('chat', '聊天应用'), ('task', '任务应用'), ('custom', '自定义应用')], default='custom', max_length=20)),
                ('renderer_key', models.SlugField(blank=True, max_length=100)),
                ('executor_key', models.SlugField(blank=True, max_length=100)),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('default_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='enterprise.organization')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applications.applicationcategory')),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['category__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAgentBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('is_default', models.BooleanField(default=False)),
                ('config_overrides', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_bindings', to='agents.agent')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_bindings', to='applications.application')),
            ],
            options={
                'db_table': 'application_agent_bindings',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChatApplicationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_message', models.TextField(blank=True)),
                ('input_placeholder', models.CharField(blank=True, max_length=200)),
                ('empty_state_title', models.CharField(blank=True, max_length=200)),
                ('allow_agent_selection', models.BooleanField(default=False)),
                ('allow_skill_selection', models.BooleanField(default=True)),
                ('allow_extra_skills', models.BooleanField(default=False)),
                ('conversation_policy', models.CharField(choices=[('new_each_open', '每次新建'), ('resume_last', '继续最近对话'), ('choose_history', '选择历史对话')], default='choose_history', max_length=30)),
                ('starter_layout', models.CharField(choices=[('cards', '卡片'), ('list', '列表'), ('compact', '紧凑')], default='cards', max_length=20)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_profile', to='applications.application')),
            ],
            options={
                'db_table': 'chat_application_profiles',
            },
        ),
        migrations.CreateModel(
            name='GuidedPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('prompt_template', models.TextField()),
                ('action', models.CharField(choices=[('fill', '填入输入框'), ('preview', '预览后发送'), ('send', '立即发送')], default='preview', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guided_prompts', to='applications.application')),
            ],
            options={
                'db_table': 'guided_prompts',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GuidedQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('help_text', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('text', '文本'), ('single_choice', '单选'), ('multi_choice', '多选'), ('number', '数字'), ('file', '文件')], max_length=30)),
                ('placeholder', models.CharField(blank=True, max_length=300)),
                ('required', models.BooleanField(default=False)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('validation', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('guided_prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='applications.guidedprompt')),
            ],
            options={
                'db_table': 'guided_questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GuidedOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='applications.guidedquestion')),
            ],
            options={
                'db_table': 'guided_options',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('private', '私有'), ('organization', '组织'), ('public', '公开')], default='private', max_length=20)),
                ('source_type', models.CharField(choices=[('bundled', '内置'), ('upload', '上传'), ('git', 'Git'), ('registry', '注册中心')], default='bundled', max_length=20)),
                ('source_uri', models.CharField(blank=True, max_length=500)),
                ('artifact_key', models.CharField(blank=True, max_length=500)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='enterprise.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationSkillBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('required', '必需'), ('default', '默认'), ('optional', '可选')], default='default', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_bindings', to='applications.application')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_bindings', to='applications.skill')),
            ],
            options={
                'db_table': 'application_skill_bindings',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='applicationagentbinding',
            constraint=models.UniqueConstraint(fields=('application', 'agent'), name='unique_application_agent_binding'),
        ),
        migrations.AddConstraint(
            model_name='guidedprompt',
            constraint=models.UniqueConstraint(fields=('application', 'key'), name='unique_guided_prompt_key'),
        ),
        migrations.AddConstraint(
            model_name='guidedquestion',
            constraint=models.UniqueConstraint(fields=('guided_prompt', 'key'), name='unique_guided_question_key'),
        ),
        migrations.AddConstraint(
            model_name='guidedoption',
            constraint=models.UniqueConstraint(fields=('question', 'value'), name='unique_guided_option_value'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_skill_slug_per_org'),
        ),
        migrations.AddConstraint(
            model_name='applicationskillbinding',
            constraint=models.UniqueConstraint(fields=('application', 'skill'), name='unique_application_skill_binding'),
        ),
    ]
