# Generated by Django 5.0.1 on 2026-09-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_applicationfavorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_default_agent',
            field=models.BooleanField(default=False),
        ),
    ]
