# Generated by Django 5.0.1 on 2026-09-11 17:41

import apps.applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_is_default_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='avatar',
            field=models.FileField(blank=True, default='', upload_to=apps.applications.models.application_avatar_upload_to),
        ),
    ]
