# Generated by Django 5.0.1 on 2026-09-05 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('conversations', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='workflow_step_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='workflows.workflowsteprun'),
        ),
        migrations.AddField(
            model_name='conversationskillbinding',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_bindings', to='conversations.conversation'),
        ),
        migrations.AddField(
            model_name='conversationskillbinding',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_bindings', to='applications.skill'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation'),
        ),
        migrations.AddConstraint(
            model_name='conversationskillbinding',
            constraint=models.UniqueConstraint(fields=('conversation', 'skill'), name='unique_conversation_skill_binding'),
        ),
    ]
