# Generated by Django 5.0.1 on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_initial'),
        ('workflows', '0002_working_directories'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='working_directory',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
