# Generated by Django 5.0.1 on 2026-09-05 15:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_conversation_working_directory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='graphflow', max_length=32)),
                ('remote_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('active', 'Active'), ('archived', 'Archived'), ('error', 'Error')], default='idle', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_thread', to='conversations.conversation')),
            ],
            options={
                'db_table': 'agent_threads',
            },
        ),
        migrations.CreateModel(
            name='AgentTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('interrupted', 'Interrupted')], default='pending', max_length=20)),
                ('input', models.JSONField(blank=True, default=list)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('error', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='conversations.agentthread')),
            ],
            options={
                'db_table': 'agent_turns',
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentServerRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_id', models.CharField(blank=True, default='', max_length=255)),
                ('method', models.CharField(max_length=128)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_requests', to='conversations.agentthread')),
                ('turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_requests', to='conversations.agentturn')),
            ],
            options={
                'db_table': 'agent_server_requests',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_id', models.CharField(max_length=255)),
                ('item_type', models.CharField(max_length=64)),
                ('status', models.CharField(blank=True, default='', max_length=32)),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('content', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='conversations.agentturn')),
            ],
            options={
                'db_table': 'agent_items',
                'ordering': ['ordinal', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agentthread',
            index=models.Index(fields=['provider', 'remote_id'], name='agent_threa_provide_0fd9f3_idx'),
        ),
        migrations.AddIndex(
            model_name='agentturn',
            index=models.Index(fields=['thread', 'status'], name='agent_turns_thread__9e43c4_idx'),
        ),
        migrations.AddIndex(
            model_name='agentserverrequest',
            index=models.Index(fields=['thread', 'status'], name='agent_serve_thread__4b49e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentitem',
            constraint=models.UniqueConstraint(fields=('turn', 'remote_id'), name='unique_agent_item_remote_id'),
        ),
        migrations.AddConstraint(
            model_name='agentserverrequest',
            constraint=models.UniqueConstraint(fields=('thread', 'turn', 'remote_id', 'method'), name='unique_agent_server_request_remote_id'),
        ),
    ]
