# Generated by Django 5.0.1 on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_application_project_working_directory'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='working_directory',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='workflowsteprun',
            name='working_directory',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
