# Generated by Django 5.0.1 on 2026-09-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_seed_default_chat'),
        ('projects', '0004_projectasset_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='application',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='projects', to='applications.application'),
        ),
        migrations.AddField(
            model_name='project',
            name='working_directory',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
