# Generated by Django 5.0.1 on 2026-09-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_backfill_project_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='template',
        ),
    ]
