# Generated by Django 5.0.1 on 2026-08-12 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='enterprise.organization'),
        ),
    ]
