# Generated by Django 5.0.1 on 2026-08-12 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_seed_personal_organizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retention_days', models.PositiveIntegerField(default=365)),
                ('redact_pii', models.BooleanField(default=True)),
                ('allowed_models', models.JSONField(blank=True, default=list)),
                ('blocked_terms', models.JSONField(blank=True, default=list)),
                ('allowed_tool_patterns', models.JSONField(blank=True, default=list)),
                ('blocked_tool_patterns', models.JSONField(blank=True, default=list)),
                ('require_tool_approval', models.BooleanField(default=True)),
                ('network_allowlist', models.JSONField(blank=True, default=list)),
                ('export_enabled', models.BooleanField(default=False)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='governance_policy', to='enterprise.organization')),
            ],
            options={
                'db_table': 'governance_policies',
            },
        ),
        migrations.CreateModel(
            name='IdentityProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('protocol', models.CharField(choices=[('oidc', 'OpenID Connect'), ('saml', 'SAML 2.0')], max_length=20)),
                ('issuer', models.CharField(max_length=500)),
                ('client_id', models.CharField(blank=True, max_length=300)),
                ('secret_ref', models.CharField(blank=True, max_length=200)),
                ('metadata_url', models.URLField(blank=True, max_length=1000)),
                ('domains', models.JSONField(blank=True, default=list)),
                ('claim_mapping', models.JSONField(blank=True, default=dict)),
                ('enforce_sso', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_providers', to='enterprise.organization')),
            ],
            options={
                'db_table': 'identity_providers',
            },
        ),
        migrations.AddConstraint(
            model_name='identityprovider',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_org_identity_provider'),
        ),
    ]
