# Generated by Django 5.2.17 on 2026-09-11 10:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeishuIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feishu_user_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('open_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('union_id', models.CharField(blank=True, default='', max_length=64)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('avatar_url', models.CharField(blank=True, default='', max_length=1000)),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feishu_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identity_feishu_identities',
            },
        ),
    ]
