# Generated by Django 5.2.17 on 2026-09-11 10:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0003_seed_wechat_article_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('supported_runtime_types', models.JSONField(blank=True, default=list)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('start_rate_limit', models.CharField(blank=True, default='', max_length=32)),
                ('max_inflight', models.PositiveIntegerField(default=100)),
                ('poll_rate_limit', models.CharField(blank=True, default='', max_length=32)),
                ('artifact_rate_limit', models.CharField(blank=True, default='', max_length=32)),
                ('timeout_seconds', models.PositiveIntegerField(default=300)),
                ('retry_policy', models.JSONField(blank=True, default=dict)),
                ('circuit_breaker', models.JSONField(blank=True, default=dict)),
                ('secret_ref', models.CharField(blank=True, default='', max_length=200)),
                ('base_url', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalog_providers',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationRuntimeBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('runtime_type', models.CharField(choices=[('agent', 'Agent'), ('workflow', 'Workflow'), ('http', 'HTTP'), ('local_task', 'Local Task'), ('media', 'Media'), ('none', 'None (fixed page)')], default='agent', max_length=20)),
                ('provider_key', models.CharField(db_index=True, max_length=64)),
                ('external_resource_id', models.CharField(blank=True, default='', max_length=255)),
                ('endpoint_key', models.CharField(blank=True, default='', max_length=120)),
                ('identity_mode', models.CharField(choices=[('user', 'User identity (UAT)'), ('tenant', 'App identity (TAT)')], default='user', max_length=20)),
                ('execution_mode', models.CharField(choices=[('interactive', 'Interactive (stream)'), ('background', 'Background (poll)')], default='interactive', max_length=20)),
                ('session_policy', models.CharField(choices=[('lazy', 'Lazy (create on first message)'), ('eager', 'Eager (create on open)')], default='lazy', max_length=20)),
                ('artifact_policy', models.CharField(choices=[('external_refresh', 'Refresh URL on access'), ('mirror_on_access', 'Mirror on first access'), ('mirror_on_complete', 'Mirror on run completion')], default='external_refresh', max_length=30)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('secret_ref', models.CharField(blank=True, default='', max_length=200)),
                ('timeout_seconds', models.PositiveIntegerField(default=300)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runtime_bindings', to='applications.application')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runtime_bindings', to='catalog.provider')),
            ],
            options={
                'db_table': 'catalog_runtime_bindings',
                'ordering': ['application_id', 'id'],
                'indexes': [models.Index(fields=['provider_key', 'runtime_type'], name='catalog_run_provide_aa63e0_idx'), models.Index(fields=['application', 'enabled'], name='catalog_run_applica_a3b6aa_idx')],
                'constraints': [models.UniqueConstraint(fields=('application', 'runtime_type', 'provider_key'), name='unique_binding_per_runtime')],
            },
        ),
    ]
