# Generated by Django 5.2.17 on 2026-09-11 10:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0003_seed_wechat_article_app'),
        ('catalog', '0001_initial'),
        ('conversations', '0004_agentthread_agentturn_agentserverrequest_agentitem_and_more'),
        ('enterprise', '0005_external_identity'),
        ('workflows', '0002_working_directories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(db_index=True, max_length=64)),
                ('runtime_type', models.CharField(db_index=True, max_length=20)),
                ('external_run_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('waiting_input', 'Waiting input'), ('waiting_external', 'Waiting external'), ('cancelling', 'Cancelling'), ('cancelled', 'Cancelled'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('interrupted', 'Interrupted')], db_index=True, default='queued', max_length=20)),
                ('provider_status', models.CharField(blank=True, default='', max_length=64)),
                ('provider_finish_reason', models.CharField(blank=True, default='', max_length=64)),
                ('input', models.JSONField(blank=True, default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('runtime_snapshot', models.JSONField(blank=True, default=dict)),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='applications.application')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='conversations.conversation')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='enterprise.organization')),
                ('runtime_binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='catalog.applicationruntimebinding')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to=settings.AUTH_USER_MODEL)),
                ('workflow_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='workflows.workflowrun')),
            ],
            options={
                'db_table': 'execution_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=64)),
                ('external_artifact_id', models.CharField(blank=True, default='', max_length=255)),
                ('provider_artifact_type', models.CharField(blank=True, default='', max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('normalized_type', models.CharField(blank=True, default='file', max_length=32)),
                ('storage_type', models.CharField(choices=[('external', 'External (provider)'), ('mirrored', 'Mirrored object storage')], default='external', max_length=20)),
                ('cached_external_url', models.TextField(blank=True, default='')),
                ('cached_url_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('cached_url_expires_at', models.DateTimeField(blank=True, null=True)),
                ('storage_key', models.CharField(blank=True, default='', max_length=500)),
                ('resolution_status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved (URL cached)'), ('expired', 'Expired'), ('failed', 'Failed'), ('mirrored', 'Mirrored')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='execution.run')),
            ],
            options={
                'db_table': 'execution_run_artifacts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_type', models.CharField(choices=[('cancel', 'Cancel'), ('respond', 'Respond (human input)'), ('resume', 'Resume')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_commands', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='execution.run')),
            ],
            options={
                'db_table': 'execution_run_commands',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence', models.PositiveBigIntegerField()),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='execution.run')),
            ],
            options={
                'db_table': 'execution_run_events',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='RunLease',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('worker_id', models.CharField(max_length=128)),
                ('lease_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lease', to='execution.run')),
            ],
            options={
                'db_table': 'execution_run_leases',
                'ordering': ['acquired_at'],
            },
        ),
        migrations.CreateModel(
            name='RuntimeAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=64)),
                ('external_attachment_id', models.CharField(blank=True, default='', max_length=255)),
                ('attachment_type', models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('feishu_doc', 'Feishu doc'), ('bitable', 'Bitable')], max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('source_type', models.CharField(choices=[('upload', 'Direct upload'), ('doc_url', 'Cloud doc reference')], default='upload', max_length=20)),
                ('source_url', models.CharField(blank=True, default='', max_length=512)),
                ('auth_mode', models.CharField(blank=True, default='', max_length=20)),
                ('auth_subject_key', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded to provider'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='conversations.conversation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runtime_attachments', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='execution.run')),
            ],
            options={
                'db_table': 'execution_runtime_attachments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['status', 'provider', 'queued_at'], name='execution_r_status_829df8_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['conversation', 'created_at'], name='execution_r_convers_96cd7d_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['user', 'created_at'], name='execution_r_user_id_a230a8_idx'),
        ),
        migrations.AddIndex(
            model_name='runartifact',
            index=models.Index(fields=['run', 'created_at'], name='execution_r_run_id_ba10ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='runartifact',
            constraint=models.UniqueConstraint(fields=('run', 'external_artifact_id'), name='unique_run_artifact_external_id'),
        ),
        migrations.AddConstraint(
            model_name='runevent',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='unique_run_event_sequence'),
        ),
        migrations.AddIndex(
            model_name='runtimeattachment',
            index=models.Index(fields=['provider', 'external_attachment_id'], name='execution_r_provide_5bbf9b_idx'),
        ),
    ]
