# Generated by Django 5.2.17 on 2026-09-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_api_key_userapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_source',
            field=models.CharField(choices=[('feishu', '飞书'), ('local_admin', '本地管理员')], db_index=True, default='local_admin', max_length=20),
        ),
    ]
