# Generated by Django 5.0.1 on 2026-09-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_auth_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_id',
            field=models.CharField(blank=True, default='', help_text='对外展示的用户 ID（工号 / 飞书 user_id）。留空则回退 FeishuIdentity.feishu_user_id，再回退本地主键', max_length=64),
        ),
    ]
