# Generated by Django 5.2.17 on 2026-09-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_agentthread_agentturn_agentserverrequest_agentitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentthread',
            name='auth_mode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='agentthread',
            name='auth_subject_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
