# Generated by Django 5.0.1 on 2026-09-05 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentskillbinding',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_bindings', to='applications.skill'),
        ),
        migrations.AddConstraint(
            model_name='agentdeployment',
            constraint=models.UniqueConstraint(fields=('agent', 'environment'), name='unique_agent_environment'),
        ),
        migrations.AddConstraint(
            model_name='agentskillbinding',
            constraint=models.UniqueConstraint(fields=('agent', 'skill'), name='unique_agent_skill_binding'),
        ),
    ]
